name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: arthur-plazanet/github-actions-kit/.github/workflows/reusable_release_publish.yml@main

    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write # create releases/tags
      id-token: write # npm provenance (OIDC)
